"""Translate the Store's small, fixed SQL surface, not arbitrary provider SQL."""

import re

from ..errors import BridgeError

QUOTED = re.compile(r"('(?:''|[^'])*'|\"(?:\"\"|[^\"])*\"|--[^\n]*(?:\n|$))")
ORDERED = {'accounts', 'sessions', 'runs', 'deleted_instances',
           'provider_inspections', 'checkpoint_restore_operations'}
REPLACEMENTS = {'instance_metadata': ('session_id', ('session_id', 'state', 'version', 'updated')),
                'provider_inspections': ('id', ('id', 'engine', 'version', 'created', 'data')),
                'recovery_workspaces': ('instance_id', ('instance_id', 'source_path', 'target_path'))}


def unquoted(sql, transform):
    return ''.join(piece if index % 2 else transform(piece)
                   for index, piece in enumerate(QUOTED.split(sql)))


def statements(script):
    parts, current = [], ''
    for index, piece in enumerate(QUOTED.split(script)):
        if index % 2:
            current += piece
            continue
        pieces = piece.split(';')
        current += pieces[0]
        for piece in pieces[1:]:
            if current.strip():
                parts.append(current.strip())
            current = piece
    if current.strip():
        parts.append(current.strip())
    return parts


def translate(statement):
    statement = re.sub(r'(?m)^\s*--[^\n]*', '', statement).strip().rstrip(';')
    create = re.match(r'CREATE TABLE IF NOT EXISTS (\w+)\s*\(', statement, re.I)
    if create:
        statement = unquoted(statement, lambda part: re.sub(
            r'\bINTEGER PRIMARY KEY AUTOINCREMENT\b',
            'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', part, flags=re.I))
        statement = unquoted(statement, lambda part: re.sub(r'\bREAL\b', 'DOUBLE PRECISION',
                                                            part, flags=re.I))
        statement = unquoted(statement, lambda part: re.sub(r'\bINTEGER\b', 'BIGINT',
                                                            part, flags=re.I))
        if create[1] in ORDERED:
            end = statement.rfind(')')
            statement = (statement[:end]
                         + ', _ab_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE'
                         + statement[end:])
    elif statement.upper().startswith('ALTER TABLE'):
        statement = unquoted(statement, lambda part: re.sub(r'\bREAL\b', 'DOUBLE PRECISION',
                                                            part, flags=re.I))
    if re.match(r'INSERT OR IGNORE\b', statement, re.I):
        statement = re.sub(r'^INSERT OR IGNORE', 'INSERT', statement, flags=re.I)
        statement += ' ON CONFLICT DO NOTHING'
    replace = re.match(r'INSERT OR REPLACE INTO (\w+)(.*)', statement, re.I | re.S)
    if replace:
        table = replace[1]
        if table not in REPLACEMENTS:
            raise BridgeError('postgres_sql_unsupported', 'This Store replacement needs a migration.')
        primary, columns = REPLACEMENTS[table]
        tail = replace[2]
        if not tail.lstrip().startswith('('):
            tail = '(' + ','.join(columns) + ')' + tail
        statement = 'INSERT INTO ' + table + tail + f' ON CONFLICT({primary}) DO UPDATE SET '
        statement += ','.join(f'{column}=excluded.{column}' for column in columns if column != primary)
    if 'sqlite_master' in statement:
        statement = statement.replace('sqlite_master',
            "(SELECT table_name AS name,'table' AS type FROM information_schema.tables "
            "WHERE table_schema=current_schema()) AS sqlite_master")
    # The reviewed Store JSON queries only read simple object fields. ->> preserves
    # SQLite's scalar text and serialized-array behavior; its boolean uses 0/1.
    statement = re.sub(r"json_extract\((\w+(?:\.\w+)?),'\$\.terminal'\)\s*=\s*1",
                       r"(\1::jsonb->>'terminal')='true'", statement)
    statement = re.sub(r"json_extract\((\w+(?:\.\w+)?),'\$\.(\w+)'\)",
                       r"(\1::jsonb->>'\2')", statement)
    statement = re.sub(r"json_type\((\w+(?:\.\w+)?),'\$\.(\w+)'\)",
                       r"(CASE jsonb_typeof(\1::jsonb->'\2') WHEN 'string' THEN 'text' "
                       r"ELSE jsonb_typeof(\1::jsonb->'\2') END)", statement)
    statement = unquoted(statement, lambda part: re.sub(r'\browid\b', '_ab_order', part))
    # Psycopg uses percent placeholders even in a query containing literal percent signs.
    statement = statement.replace('%', '%%')
    return unquoted(statement, lambda part: part.replace('?', '%s'))
